### ISSUE TITLE
Outside click to hide wallet connector (login) dropdown

### ISSUE THREAD

**Issue by jeffishjeff** [daicostarter/issues#1]
![image](https://user-images.githubusercontent.com/5304123/45205806-dd836280-b2b5-11e8-9a8d-9e4a61662d89.png)

**Comment by chaningHuang** [comment]
![45293729-92728500-b52b-11e8-8063-3c2180dd3459](https://user-images.githubusercontent.com/7642894/45728340-1c8cae80-bbfa-11e8-8e2a-5302781da188.gif)

**Comment by crawlregister** [comment]
verified
