### ISSUE TITLE
Implement Privacy Policy page

### ISSUE THREAD

**Issue by jeffishjeff** [daicostarter/issues#10]

**Comment by chaningHuang** [comment]
![screencapture-localhost-8081-dsweb-privacypolicy-2018-09-19-11_00_49](https://user-images.githubusercontent.com/7642894/45728660-8194d400-bbfb-11e8-9c04-0b9c33361a5e.png)

**Comment by chaningHuang** [comment]
![image](https://user-images.githubusercontent.com/7642894/45729074-61feab00-bbfd-11e8-8273-6f666f12eb97.png)

**Comment by jeffishjeff** [comment]
Incorporation related issues tracked by #51
