### ISSUE TITLE
Implement Cookie Policy page

### ISSUE THREAD

**Issue by jeffishjeff** [daicostarter/issues#11]

**Comment by chaningHuang** [comment]
![screencapture-localhost-8081-dsweb-privacypolicy-2018-09-19-11_00_49](https://user-images.githubusercontent.com/7642894/45728633-56aa8000-bbfb-11e8-9d49-26cd3c5296bd.png)

**Comment by chaningHuang** [comment]
![screencapture-localhost-8081-dsweb-cookiepolicy-2018-09-19-11_02_52](https://user-images.githubusercontent.com/7642894/45728676-9d987580-bbfb-11e8-9ec9-d19c6ab7bac2.png)
