### ISSUE TITLE
Write "What is DAICO?"

### ISSUE THREAD

**Issue by jeffishjeff** [daicostarter/issues#16]

**Comment by chaningHuang** [comment]
![image](https://user-images.githubusercontent.com/7642894/45728534-eac81780-bbfa-11e8-95e1-238e230a3da2.png)
页面样式已经调整好了

**Comment by chaningHuang** [comment]
FAQ page
![image](https://user-images.githubusercontent.com/7642894/45749297-cfcac700-bc3d-11e8-81f1-152dd4b9e872.png)

Detail page
![screencapture-localhost-8081-dsweb-whatisdaico-2018-09-19-18_57_36](https://user-images.githubusercontent.com/7642894/45749318-e5d88780-bc3d-11e8-832c-16c2f2185e6b.png)
