### ISSUE TITLE
Write "What is DaicoStarter?"

### ISSUE THREAD

**Issue by jeffishjeff** [daicostarter/issues#17]

**Comment by chaningHuang** [comment]
![image](https://user-images.githubusercontent.com/7642894/45728426-8c029e00-bbfa-11e8-833f-51791d70c69c.png)
页面样式已经调整好

**Comment by chaningHuang** [comment]
![image](https://user-images.githubusercontent.com/7642894/45728499-ccfab280-bbfa-11e8-81c8-db4a1752f919.png)
页面样式已经调整好

**Comment by chaningHuang** [comment]
FAQ page
![image](https://user-images.githubusercontent.com/7642894/45749129-5501ac00-bc3d-11e8-8753-a48b596ecb4a.png)

Detail page
![screencapture-localhost-8081-dsweb-whatisdaicostarter-2018-09-19-18_54_25](https://user-images.githubusercontent.com/7642894/45749190-7498d480-bc3d-11e8-9833-74c139034c36.png)
