### ISSUE TITLE
better design for table with no content 

### ISSUE THREAD

**Issue by crawlregister** [daicostarter/issues#24]
![image](https://user-images.githubusercontent.com/6903108/45260367-9feb1a80-b418-11e8-93a0-1841213a6a48.png)

**Comment by chaningHuang** [comment]
![image](https://user-images.githubusercontent.com/7642894/45793491-f97b0100-bcc4-11e8-8439-d437e4d42fbf.png)
![image](https://user-images.githubusercontent.com/7642894/45793514-13b4df00-bcc5-11e8-90f0-2ad542160329.png)

**Comment by crawlregister** [comment]
@chaningHuang 
![image](https://user-images.githubusercontent.com/6903108/45858339-9013f480-bd8f-11e8-9284-b50fd9499fa9.png)

watchlist table not fixed

**Comment by crawlregister** [comment]
problem solved
verified on dsweb
