### ISSUE TITLE
design for account/mydaico page error display 

### ISSUE THREAD

**Issue by crawlregister** [daicostarter/issues#25]
![image](https://user-images.githubusercontent.com/6903108/45260516-674d4000-b41c-11e8-9488-13656931b109.png)

**Comment by hoyaHuang** [comment]
![image](https://user-images.githubusercontent.com/7642894/45288295-e9249280-b51c-11e8-9c3e-24cec6bc718b.png)
增加了加载错误显示样式

**Comment by jeffishjeff** [comment]
Please make sure an issue belongs to a project and also a milestone.

Also that implementor must assign the issue to QA or downstream (i.e. web designer to front end dev) or issue reporter to close
