### ISSUE TITLE
kyc personal info page - what to show when there is no id type available for selected country

### ISSUE THREAD

**Issue by crawlregister** [daicostarter/issues#26]
![image](https://user-images.githubusercontent.com/6903108/45261986-8ad5b200-b43f-11e8-8516-8b493ef33934.png)

**Comment by chaningHuang** [comment]
![kyc](https://user-images.githubusercontent.com/7642894/45810139-88574000-bcfc-11e8-8db9-a41d46a4b74c.gif)

**Comment by crawlregister** [comment]
![image](https://user-images.githubusercontent.com/6903108/45858308-635fdd00-bd8f-11e8-8275-29deb8072e21.png)

problem solved
tested in dsweb
