### ISSUE TITLE
Display wallet address in compact format

### ISSUE THREAD

**Issue by jeffishjeff** [daicostarter/issues#3]
![image](https://user-images.githubusercontent.com/5304123/45206168-eaed1c80-b2b6-11e8-8ae9-86b164dd2f14.png)

**Comment by chaningHuang** [comment]
![image](https://user-images.githubusercontent.com/7642894/45728300-e8b18900-bbf9-11e8-8f5a-0ba94845a91c.png)

**Comment by crawlregister** [comment]
verified
created a compact string util function to handle upload photo filenames and wallet address display.
