### ISSUE TITLE
Display 'No DAICO found' or something like that instead of empty table

### ISSUE THREAD

**Issue by jeffishjeff** [daicostarter/issues#34]
![image](https://user-images.githubusercontent.com/5304123/45728029-cd924980-bbf8-11e8-9121-3df934aa30cf.png)

**Comment by chaningHuang** [comment]
![image](https://user-images.githubusercontent.com/7642894/45793491-f97b0100-bcc4-11e8-8439-d437e4d42fbf.png)
![image](https://user-images.githubusercontent.com/7642894/45793514-13b4df00-bcc5-11e8-90f0-2ad542160329.png)

**Comment by crawlregister** [comment]
problem solved
verified on dsweb
