### ISSUE TITLE
Add KYC error message style 

### ISSUE THREAD

**Issue by crawlregister** [daicostarter/issues#37]
![image](https://user-images.githubusercontent.com/6903108/45736108-96359400-bc1c-11e8-881b-0dd7e1ff4a14.png)

**Comment by chaningHuang** [comment]
![image](https://user-images.githubusercontent.com/7642894/45811620-2993c580-bd00-11e8-9cb5-32db218c1904.png)

**Comment by crawlregister** [comment]
Problem solved.
Tested with mock data.
