### ISSUE TITLE
error message not on the 1st screen

### ISSUE THREAD

**Issue by crawlregister** [daicostarter/issues#38]
try adjust the layout to include error in the 1st screen. 

![image](https://user-images.githubusercontent.com/6903108/45737666-05ad8280-bc21-11e8-897a-175b059b0014.png)

**Comment by chaningHuang** [comment]
![image](https://user-images.githubusercontent.com/7642894/45808151-b5edba80-bcf7-11e8-8dec-8e3ba22f3d92.png)

**Comment by crawlregister** [comment]
![image](https://user-images.githubusercontent.com/6903108/45857763-ec294980-bd8c-11e8-9eee-851dd9fe7b04.png)
tested in dsweb
problem solved
