### ISSUE TITLE
add tooltip for kyc uploaded filename

### ISSUE THREAD

**Issue by crawlregister** [daicostarter/issues#39]
tooltip for filename
![image](https://user-images.githubusercontent.com/6903108/45738056-04c92080-bc22-11e8-898d-8b33a14c35cf.png)

**Comment by chaningHuang** [comment]
![image](https://user-images.githubusercontent.com/7642894/45749984-f984ed80-bc3f-11e8-8722-124169d43b15.png)

**Comment by crawlregister** [comment]
![image](https://user-images.githubusercontent.com/6903108/45857818-2bf03100-bd8d-11e8-94a0-cb8618bad90f.png)
problem solved
tested on dsweb
also tested with very long file name, it works well.
