### ISSUE TITLE
Issues with link to Start a DAICO

### ISSUE THREAD

**Issue by jeffishjeff** [daicostarter/issues#4]
![image](https://user-images.githubusercontent.com/5304123/45206343-5f27c000-b2b7-11e8-9dde-4457fc1a24d9.png)

**Comment by chaningHuang** [comment]
![image](https://user-images.githubusercontent.com/7642894/45728369-52ca2e00-bbfa-11e8-8c2b-83b702fb499f.png)

**Comment by crawlregister** [comment]
verified
