### ISSUE TITLE
Issues found on ongoing campaign

### ISSUE THREAD

**Issue by frasierw** [daicostarter/issues#41]
1. Time Remaining is Ended when the poll actually hasn't started
2. Current Tap is not correct.
3. Token should be 'QA1' instead of 'PPP'

Also, suggest to change "Vote" to "View" as user can't vote on an unstarted poll

<img width="1280" alt="screen shot 2018-09-19 at 10 38 19 pm" src="https://user-images.githubusercontent.com/9762691/45760569-efbdb300-bc5c-11e8-9a60-9eacb1a5c526.png">

**Comment by crawlregister** [comment]
all three issues have been fixed

**Comment by frasierw** [comment]
Verified

![screen shot 2018-09-21 at 7 13 38 pm](https://user-images.githubusercontent.com/9762691/45878179-c3c43e00-bdd2-11e8-8da3-620298ec4b90.png)
