### ISSUE TITLE
Tap amount in tap poll title is not correct

### ISSUE THREAD

**Issue by frasierw** [daicostarter/issues#48]
![screen shot 2018-09-21 at 7 29 48 pm](https://user-images.githubusercontent.com/9762691/45878737-c6279780-bdd4-11e8-839d-12ea31828680.png)
![screen shot 2018-09-21 at 7 29 56 pm](https://user-images.githubusercontent.com/9762691/45878738-c6279780-bdd4-11e8-9187-6f56760217f1.png)

**Comment by crawlregister** [comment]
problem solved
![image](https://user-images.githubusercontent.com/6903108/45880170-a9419300-bdd9-11e8-9132-b232b1bb3ca3.png)
![image](https://user-images.githubusercontent.com/6903108/45880183-b068a100-bdd9-11e8-9767-3c5c19dbc2dd.png)
![image](https://user-images.githubusercontent.com/6903108/45880197-bbbbcc80-bdd9-11e8-9577-e6161f961c9b.png)
