### ISSUE TITLE
Create email groups

### ISSUE THREAD

**Issue by jeffishjeff** [daicostarter/issues#50]
- business@daicostarter.com
- media@daicostarter.com

**Comment by jeffishjeff** [comment]
done

**Comment by tsingyi** [comment]
@jeffishjeff 目前看来是国内的服务商提供的邮箱似乎都不能正常的发送到我们的邮箱。

|from| with attachment? | to | result |
|-|-|-|-|
|qq.com | yes | business@daicostarter.com | ![#f03c15](https://placehold.it/15/f03c15/000000?text=+) `Not Received` |
|qq.com | no | business@daicostarter.com |  ![#f03c15](https://placehold.it/15/f03c15/000000?text=+) `Not Received`|
|163.com | yes | business@daicostarter.com |  ![#f03c15](https://placehold.it/15/f03c15/000000?text=+) `Not Received` |
|163.com | no | mail@daicostarter.com |  ![#f03c15](https://placehold.it/15/f03c15/000000?text=+) `RETURNED` |
|protonmail.com | yes | business@daicostarter.com | ![#c5f015](https://placehold.it/15/c5f015/000000?text=+) `SUCCESS` |
|protonmail.com | no  | business@daicostarter.com | ![#c5f015](https://placehold.it/15/c5f015/000000?text=+) `SUCCESS` |
|protonmail.com | no  | media@daicostrater.com | ![#c5f015](https://placehold.it/15/c5f015/000000?text=+) `SUCCESS`|
|outlook.com | yes | media@daicostarter.com |  ![#f03c15](https://placehold.it/15/f03c15/000000?text=+) `RETURNED` |

<img width="1023" alt="screen shot 2018-09-26 at 12 14 06" src="https://user-images.githubusercontent.com/6947982/46056941-c41f5900-c185-11e8-8d71-738ee5c12b8d.png">

<img width="880" alt="screen shot 2018-09-26 at 12 13 47" src="https://user-images.githubusercontent.com/6947982/46056945-c8e40d00-c185-11e8-8b27-0e8a2ae7c303.png">

**Comment by tsingyi** [comment]
Received Reply Mail Count

|mail provider| count |
|-|-|
|qq.com| 1 |
|163.com | 2|
|protonmail.com|3|
|outlook.com|1|
