### ISSUE TITLE
 Contribute limit display wrong

### ISSUE THREAD

**Issue by chaningHuang** [daicostarter/issues#52]
![image](https://user-images.githubusercontent.com/7642894/45989651-28231e00-c0af-11e8-90ac-94c7483c5058.png)
1. 样式没显示全
2. 0.20 ~ 0.00

**Comment by crawlregister** [comment]
problem solved.

![image](https://user-images.githubusercontent.com/6903108/46077400-52fe9680-c1c3-11e8-8621-648f4acc7883.png)

**Comment by chaningHuang** [comment]
style fixed.
![image](https://user-images.githubusercontent.com/7642894/46130267-711fd180-c26b-11e8-8759-2373b448927a.png)
