### ISSUE TITLE
Reduce footer spacing

### ISSUE THREAD

**Issue by jeffishjeff** [daicostarter/issues#6]
![image](https://user-images.githubusercontent.com/5304123/45206402-7bc3f800-b2b7-11e8-9b25-156e25877124.png)

**Comment by chaningHuang** [comment]
![image](https://user-images.githubusercontent.com/7642894/45728229-adaf5580-bbf9-11e8-8ab6-fa92bc191a96.png)
高度已经完成调整

**Comment by jeffishjeff** [comment]
Still too much whitespace IMHO, but will revisit after Terms of Use, Privacy Policy, and Cookie Policy links are added. Close for now
