### ISSUE TITLE
searchable dropdown list

### ISSUE THREAD

**Issue by jeffishjeff** [daicostarter/issues#8]
![image](https://user-images.githubusercontent.com/5304123/45206444-9eeea780-b2b7-11e8-868b-15cb03969c93.png)

**Comment by chaningHuang** [comment]
![45293696-7e2e8800-b52b-11e8-89b1-ae5a4bcfd39e](https://user-images.githubusercontent.com/7642894/45728161-61fcac00-bbf9-11e8-9568-76dd29e48115.gif)

**Comment by crawlregister** [comment]
problem solved.
So far searchable dropdown list only applied to Country input in 'Start a Daico' page and nationality input in KYC page.
verified on dsweb
