### ISSUE TITLE
Implement Terms of Use page

### ISSUE THREAD

**Issue by jeffishjeff** [daicostarter/issues#9]

**Comment by chaningHuang** [comment]
![image](https://user-images.githubusercontent.com/7642894/45728770-126baf80-bbfc-11e8-9e28-9ffbb4668c34.png)

**Comment by chaningHuang** [comment]
![image](https://user-images.githubusercontent.com/7642894/45728971-02a09b00-bbfd-11e8-9453-62789108d793.png)
![image](https://user-images.githubusercontent.com/7642894/45728988-1815c500-bbfd-11e8-9a80-3cf67ef5047c.png)
等待替换的内容

**Comment by jeffishjeff** [comment]
Incorporation related issues tracked by #51

Rulebook tracked by #49
